export {default as Github} from './github'
export {default as Covid} from './covid'
export {default as WashHand} from './wash-your-hands'
export {default as SocialDistance} from './social-distance'
export {default as Mask} from './mask'
export {default as CoverCough} from './cover-cough'
export {default as Clean} from './clean'
export {default as Healthcare} from './healthcare'
